server:
  port: ${SERVER_PORT}

spring:
  datasource:
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    url: jdbc:mysql://localhost:3306/db_users?createDatabaseIfNotExists=true?autorecconect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2MB
      
  mail:
    host: sandbox.smtp.mailtrap.io
    port: ${MAILTRAP_PORT}
    username: ${MAILTRAP_USER}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl: false
          starttls:
            enable: true
            